
export type PropertyType = 
  | 'text' 
  | 'number' 
  | 'select' 
  | 'multi_select' 
  | 'status'
  | 'date' 
  | 'person' 
  | 'files_and_media' 
  | 'checkbox' 
  | 'url' 
  | 'email' 
  | 'phone'
  | 'formula'
  | 'relation'
  | 'rollup'
  | 'created_time'
  | 'created_by'
  | 'last_edited_time'
  | 'last_edited_by'
  | 'id';
