// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwntvuhhplzkbvogggkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bnR2dWhocGx6a2J2b2dnZ2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDg4MTQsImV4cCI6MjA2NTA4NDgxNH0.bJHYbDiNAFwD2y7i9ERPKob3DJfIVvNH4zYh5bv2K_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);